repositoryUrl: git@github.com:boxcee/semantic-release-jira-releases.git
branch: master
dryRun: false
debug: false
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - - '@semantic-release/npm'
    - npmPublish: true
  - - '@semantic-release/git'
    - assets:
        - package.json
        - CHANGELOG.md
  - - '@semantic-release/github'
    - failComment: false
